### ISSUE TITLE
Localization options

### ISSUE THREAD

**Issue by justinkenel** [lhncbc/lforms#74] opened 2021-11-01 20:45 UTC
Hello! I am looking to set localization settings when rendering LForms - specifically, setting the placeholder text on inputs so that a Spanish language form has Spanish placeholder text:

![image](https://user-images.githubusercontent.com/2307171/139739521-0ac88df5-4a23-466a-b91b-aff3e8479526.png)

Is this currently supported? I wasn't able to find anything that said one way or another. If it's not, I'd be interested in a nudge in the right direction for establishing that, or helping out with an existing effort to do so.

**Comment by plynchnlm** [comment] 2021-11-01 21:00
I think this is a duplicate of https://github.com/lhncbc/lforms/issues/70.  However, it is good to know we now have three requests for adding the ability show text in another language, so thanks for the report.  We are currently rewriting lforms to get off of AngularJS, and might be able to look at this next year.

**Closed by plynchnlm** 2021-11-01 21:00 UTC

**Comment by justinkenel** [comment] 2021-11-02 13:57
Thanks @plynchnlm - is all work on the current angular based version paused pending the migration / would you accept a PR modifying it?

**Comment by plynchnlm** [comment] 2021-11-02 17:17
AngularJS is going to be unsupported at the end of this year.  https://docs.angularjs.org/misc/version-support-status.  So, we really need to focus on completing the rewrite in Angular (different from AngularJS), which will be a Angular-based web component.
