### ISSUE TITLE
Is it possible to use the lforms npm module within a React app?

### ISSUE THREAD

**Issue by MJ422** [lhncbc/lforms#19] opened 2019-12-17 19:29 UTC
I wanted to explore the possibilities of the lforms functionality outside of bringing the CDN in to an html page and working within those constraints.

Would it be possible to leverage the lforms npm module within a React application created, and still successfully render the LForms widget on the view?

**Comment by plynchnlm** [comment] 2019-12-17 19:51
I can't think why using it as an npm module would make a difference.  We just tried including LForms in a React app we have (by adding the tags to the pre-built versions, not via npm) and both the form and the React app seemed to co-exist happily.

**Comment by MJ422** [comment] 2019-12-17 20:11
Great, thank you for the feedback. I wanted to pursue this use-case but was not sure. Thanks for your prompt reply!

**Comment by MJ422** [comment] 2019-12-27 19:47
Is there a certain way that the methods in these modules need to be imported in to a node file?

Currently, I have 'lforms' and '@lhncbc' modules in my node_modules directory for my React App brought in using the _require()_ method, such as "const LForms = require('lforms'); "

 I just wanted to drop in and see if you had any advice as to why I am unable to use this lforms npm package. I continually get the following error when trying to use this module: 

![image](https://user-images.githubusercontent.com/44490162/71530304-1a160b80-28b7-11ea-9fa8-bfd5dc56dbee.png)

**Comment by MJ422** [comment] 2019-12-30 16:54
Hi, just wanted to get some advice and/or guidance on the implementation of this lforms NPM module within a React/Node.js project. I am continually met with errors when attempting to import this file in to a javascript file within a very small React project.

![image](https://user-images.githubusercontent.com/44490162/71591608-fe9b4280-2afa-11ea-859e-c062f2219a76.png)

I am also a bit confused by the examples on Runkit. I seem to continually hit a DOM/BOM related issue on the Runkit examples linked on the [npm module page](https://npm.runkit.com/lforms) (see below):
![image](https://user-images.githubusercontent.com/44490162/71591655-25f20f80-2afb-11ea-94b6-b681174fa0f8.png)

**Comment by plynchnlm** [comment] 2020-01-02 16:14
The error in your IDE indicates it is expecting the module to be TypeScript.  It is just regular JavaScript.  I don't use TypeScript, so I am not sure what to suggest, but my understanding was that JavaScript could be used with TypeScript code.

I had never seen the RunKit example before.  I suspect it is autogenerated.  The error you see there is the result of trying to require lforms from within Node.  The lforms package works in a browser, and not within Node.js.  Are you trying to use it server-side?

**Comment by MJ422** [comment] 2020-01-02 19:02
> The error in your IDE indicates it is expecting the module to be TypeScript. It is just regular JavaScript. I don't use TypeScript, so I am not sure what to suggest, but my understanding was that JavaScript could be used with TypeScript code.
> 
> I had never seen the RunKit example before. I suspect it is autogenerated. The error you see there is the result of trying to require lforms from within Node. The lforms package works in a browser, and not within Node.js. Are you trying to use it server-side?

Yes, we were trying to leverage this [npm package](https://www.npmjs.com/package/lforms) in a node environment. Our idea was to have handler functions call for FHIR questionnaire resources on the server side, then use that package's built-in methods to generate LForms data to display in React components. On top of this, also use the built-in methods to generate QuestionnaireResponse resources out of the input in to the LForm in the view. 

> I can't think why using it as an npm module would make a difference. We just tried including LForms in a React app we have (by adding the tags to the pre-built versions, not via npm) and both the form and the React app seemed to co-exist happily.

How exactly did you implement this, if I may ask? In your latest response, you mention that the [lforms package](https://www.npmjs.com/package/lforms) only works in a browser and not in a local node environment. 

I appreciate your continued support, and look forward to hearing from you!

**Comment by plynchnlm** [comment] 2020-01-03 22:33
Although it is an npm package, it is intended for the browser, not to be run in Node.js.  As with other npm packages like AngularJS or jQuery, you need to package up (and probably transpile) the files to be run in the browser (e.g. with webpack).

In our test in our React app, we just used the browser-ready version (which is built from the same files via webpack) by including the URLs from the website we've hosted those, as documented at http://lhncbc.github.io/lforms/#installation.  (There are two URLs, one for the CSS and one for the JavaScript.)  Note that the latest version is now 20.1.2.  (The documentation says version 17, which was the latest then, but the same documentation applies.)

**Comment by yunwwang** [comment] 2020-03-06 14:36
Do you have an example for React app? I am still confused how to integrate lforms to react component

**Comment by plynchnlm** [comment] 2020-03-06 15:47
I have not tried integrating LForms in a React component.  What we did try was including the pre-built versions using script/link tags (as described at http://lhncbc.github.io/lforms/#installation) in a page with a React app, and both the LForms display and the React app worked, but independently.

**Comment by plynchnlm** [comment] 2021-10-29 20:44
It is actually already an npm package:  https://www.npmjs.com/package/lforms.  This issue here is that it is intended to be run in the browser, and needs to be transpiled with webpack to something the browser can understand.  If you are using webpack for your React app, it should be possible to pull in the lforms npm package.  If you are not using webpack, well, I don't know but I suspect there will be some issues with getting it built.  There is currently a mix of require and import statements, which I think cause a problem for some other build systems.

**Comment by okongwu101** [comment] 2022-06-12 20:59
> I can't think why using it as an npm module would make a difference. We just tried including LForms in a React app we have (by adding the tags to the pre-built versions, not via npm) and both the form and the React app seemed to co-exist happily.

Please can you provide a simple example to illustrate your implementation. Thank you.

**Comment by plynchnlm** [comment] 2022-06-13 21:13
@lhcye Created this example of a React app using the lforms webcomponent (version 30.3.0):  https://codepen.io/lhcye/pen/KKQbbwZ
For some reason the same example does not work in JSFiddle, but I guess that might have to do with how JSFiddle loads JavaScript libraries.

**Comment by plynchnlm** [comment] 2022-06-14 15:26
Closing, as the current version of lforms, which is a web component, does not have an npm version.  We are hoping to get that working again, probably starting with an Angular component as a npm package.  The issue is that when Angular builds the web component, it bundles all of the dependencies, and it does not make sense to publish bundled files as an npm package.  Also, even if we did that, "import" statements to pull in the files might not work, depending on which build system you use.  Anyway, the built files are available from https://clinicaltables.nlm.nih.gov/lforms-versions and can be downloaded from there, if you don't wish to run the build yourself.

**Closed by plynchnlm** 2022-06-14 15:26 UTC

**Comment by okongwu101** [comment] 2022-06-14 16:03
> Closing, as the current version of lforms, which is a web component, does not have an npm version. We are hoping to get that working again, probably starting with an Angular component as a npm package. The issue is that when Angular builds the web component, it bundles all of the dependencies, and it does not make sense to publish bundled files as an npm package. Also, even if we did that, "import" statements to pull in the files might not work, depending on which build system you use. Anyway, the built files are available from https://clinicaltables.nlm.nih.gov/lforms-versions and can be downloaded from there, if you don't wish to run the build yourself.

I saw your response and i really appreciate the effort. Still trying to get it to work though. Am using Next JS not Angular. I think your last comment explains it. If i am understanding the issue correctly, the built files won't work with react frameworks as they were built with/for angular (please correct me if am wrong).

**Comment by plynchnlm** [comment] 2022-06-14 16:29
How are you installing it?

**Comment by plynchnlm** [comment] 2022-06-14 19:44
Also, you did not mention whether you looked at the codepen example I posted above.  Did you take a look at that?

**Comment by okongwu101** [comment] 2022-06-14 19:49
1: Download the built zip. The latest version.
2: Extract the folder.
3: Save the folder to root directory of my NextJS project
4: Consume / import (whatever the term is) the scripts and css file in my pages using the script tag
5: In the JSX create a location to display the form
6: Run the 'LForms.Util.addForm......' with required arguments to display a form. Then all hell break loose.
7: Error: LForms is undefined.

**Comment by okongwu101** [comment] 2022-06-14 20:38
> Also, you did not mention whether you looked at the codepen example I posted above. Did you take a look at that?

I mentioned above that i looked at it. I also thanked you. Still trying to get it. Am more familiar with functional components. Pardon my green horns.

**Comment by plynchnlm** [comment] 2022-06-15 20:12
We're not familiar with NextJS, though we've heard of it.  Perhaps you could share an example showing the problem on CodePen?

**Comment by okongwu101** [comment] 2022-06-17 10:52
> We're not familiar with NextJS, though we've heard of it. Perhaps you could share an example showing the problem on CodePen?

https://codesandbox.io/s/lhforms-ywh1xx?file=/pages/index.js

**Comment by plynchnlm** [comment] 2022-06-17 19:05
Looking at index.js in that example, it would seem that LForms is being used before you are returning the HTML that loads the LForms JS.  Those files need to be loaded before LForms is used.

**Comment by lhcye** [comment] 2022-06-17 19:44
"LForms" probably needs to be "window.LForms". LForms is added to window when the js files are loaded. 

I am not familiar with NextJs. You need to make sure all the LForms js files are loaded before you can use window.LForms.
